# Generated by Django 5.1.7 on 2025-03-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_be_shared',
            new_name='can_data_be_shared',
        ),
    ]
