# Generated by Django 5.1.7 on 2025-03-26 16:27

import authentication.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_can_be_shared_user_can_data_be_shared'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(validators=[authentication.models.validate_age]),
        ),
    ]
